apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Chart.Name }}"
{{- if .Values.Annotations }}
  annotations:
{{ toYaml .Values.Annotations | indent 4 }}
{{- end }}
spec:
  replicas: 1
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.Image }}:{{ .Values.ImageTag }}"
        name: {{ .Chart.Name }}
        command: ["/exposecontroller"]
        args:
        - --daemon
{{- range .Values.Args }}
        - {{ . | quote }}
{{- end }}
      serviceAccountName: {{ .Chart.Name }}
